### ISSUE TITLE
Python 3.13 wheels (non free-threaded) are not available

### ISSUE THREAD

**Issue by RobPasMue** [crate-py/rpds#110]
Hi all! This is my first issue here... please let me know if you need any more information

``rpds-py`` did a new release yesterday. However, this new release seems to ship only the Python 3.13 wheels for free-threaded mode. If you are using Python 3.13 without the free-threaded mode... you are required to build it from scratch:

![image](https://github.com/user-attachments/assets/ed1ba9f6-b5e3-4fc1-950d-59388b9ea837)

The wheel files have a subtle difference (which is ``cp313t`` instead of ``cp313``):

![image](https://github.com/user-attachments/assets/3919a2fc-2fa7-49b8-9eea-50674dedc8a5)

For MacOS and ManyLinux, this has been addressed and the distributions for both free-threaded and not free-threaded have been uploaded, but for Windows this is not the case.

Can we get this resolved? Could we also upload the standard 3.13 wheels for Windows? Thanks in advance!

**Comment by RobPasMue** [comment]
It looks like installing both 3.13 and 3.13 free-threaded mode on Windows is a colliding operation using the ``quansight-labs/setup-python@v5`` action... and the system registry might be getting confused. Maybe splitting the job in 2 for 3.13 does the trick? I can propose a PR with this change

**Comment by Julian** [comment]
I'll have a look at your PR later today -- have / can you raise the issue upstream with the quantsight-labs action, that seems important? 

And thanks for raising!

CC @ngoldbaum

**Comment by RobPasMue** [comment]
Sounds good! Will do :) thanks @Julian!
