### ISSUE TITLE
Issue with v0.22.0

### ISSUE THREAD

**Issue by epenet** [crate-py/rpds#112]
Home Assistant has pinned to version 0.21.0 because CI is failing on a couple of dependencies referencing `jsonschema` (and therefore `referencing` and `rpds-py`)
See https://github.com/home-assistant/core/actions/runs/12126261540/job/33808489106 for the CI failure
See https://github.com/home-assistant/core/pull/132170 for the pinning of the library

I was able to reproduce locally on a python 3.13 dev container.
Running `python3 -X dev` then `import jsonschema` caused the segfault

**Comment by Julian** [comment]
I haven't looked carefully but this seems pretty likely to be https://github.com/PyO3/pyo3/issues/4757 which can be fixed when there's a fix upstream.

**Comment by davidhewitt** [comment]
Looking at your CI, I think it is. Working on a fix as a matter of urgency.

**Comment by epenet** [comment]
Thanks for the quick fix 👍
