### ISSUE TITLE
v0.8.8: Bitdefender quarantines "infected" rpds.cp311-win_amd64.pyd

### ISSUE THREAD

**Issue by estaub** [crate-py/rpds#12]
I've no idea whether this is real or not, but Bitdefender (an anti-virus app) immediately flags and quarantines one of the files created upon install:

> The file C:\Users\estau\.virtualenvs\process_wavelength\Lib\site-packages\rpds\rpds.cp311-win_amd64.pyd is infected with Gen:Suspicious.Cloud.4.Bu4@a4QxQep and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

I'd guess this only shows up on systems with AMD processors.

**Comment by estaub** [comment]
If someone wants to report it as a false positive, see https://www.bitdefender.com/consumer/support/answer/29358/ .  I'm not going to because I have no basis on which to judge.

**Comment by Julian** [comment]
I have little interest myself as virus detectors are <no comment> :).
