### ISSUE TITLE
Wheels for Python 3.12

### ISSUE THREAD

**Issue by M5oul** [crate-py/rpds#13]
Hi,

There is no wheels built and distributed for Python 3.12.
This package is now a dependency  of [`jsonschema` v4.18.0](https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst#v4180).

To allow software testing against Python 3.12 which is in beta state, that would be great if you could provide Py3.12 wheels.

Thanks.

**Comment by Julian** [comment]
Done in 6a54caf313d8d1dec9d59042d1b6b88b46f349fc, this will be out momentarily in v0.8.10.
