### ISSUE TITLE
Add pre-built manylinux package for pypy 3.10

### ISSUE THREAD

**Issue by felipou** [crate-py/rpds#14]
Pypy 3.10 was released about a month ago, it would be nice to have pre-built packages for it!
https://www.pypy.org/posts/2023/06/pypy-v7312-release.html

It seems manylinux already included it: https://github.com/pypa/manylinux/commit/d833a5fc05a59dadfe302651481e11fbfa66fe59

So I guess we only need to update this line?
https://github.com/crate-py/rpds/blob/a4fc5c25e8578550aab9120c28e91e62d936cb93/.github/workflows/CI.yml#L87C9-L87C9

I don't have any experience with github workflows/actions though.

**Comment by Julian** [comment]
Done in 6a54caf313d8d1dec9d59042d1b6b88b46f349fc, this will be out momentarily in v0.8.10.
