### ISSUE TITLE
Built distribution (wheel) for armv6

### ISSUE THREAD

**Issue by marceloalencar** [crate-py/rpds#19]
ARMv6 is still a common platform, as used in Raspberry Pi (original), and should have wheels built.
This should reduce time compiling from source and fix projects depending on `rpds-py` through dependencies such as https://github.com/dgtlmoon/changedetection.io/issues/1708
Thanks in advance.

**Comment by Julian** [comment]
I don't think this is actually possible / that PyPI supports wheels tagged with armv6, at least as far as I know.

Users on RPi I think have to rely on piwheels.

**Comment by marceloalencar** [comment]
An issue has been filled on piwheels: https://github.com/piwheels/packages/issues/380
