### ISSUE TITLE
release 0.10.1 Cargo.toml references the previous version 

### ISSUE THREAD

**Issue by rawlingsj** [crate-py/rpds#22]
After a quick look I think a version update was needed during the release process?  I.e. should this

https://github.com/crate-py/rpds/blob/3eac1e7f9b05fa966526b6d4d56584659f72ad90/Cargo.toml#L3C1-L3C19 

be `0.10.1`?

**Comment by Julian** [comment]
Thanks! Yep... I still haven't found a decent way to reliably do this in Rust without being able to forget, it's a bit annoying. But should be fixed (in another release).
