### ISSUE TITLE
Latest release tagged as v0.31.2

### ISSUE THREAD

**Issue by ajayk** [crate-py/rpds#38]
The latest release is tagged as [v0.31.2](https://github.com/crate-py/rpds/releases/tag/v0.31.2)  was this supposed to be v0.13.2 instead as the pypi versions version points to v0.13.2 https://pypi.org/project/rpds-py/  And all the release artifacts points to v0.13.2 in the whl versions

**Comment by Julian** [comment]
Thanks, fixed
