### ISSUE TITLE
Couldn't find a setup script

### ISSUE THREAD

**Issue by mjallday** [crate-py/rpds#43]
```
Installed /home/circleci/my-project/.venv/lib/python3.10/site-packages/SecretStorage-3.3.3-py3.10.egg
Searching for rpds-py>=0.7.1
Reading https://pypi.org/simple/rpds-py/
Downloading https://files.pythonhosted.org/packages/48/0b/f42f99419c5150c2741fe28bf97674d928d46ee17f46f2bc5be031cce0bc/rpds_py-0.13.2.tar.gz#sha256=f8eae66a1304de7368932b42d801c67969fd090ddb1a7a24f27b435ed4bed68f
Best match: rpds-py 0.13.2
Processing rpds_py-0.13.2.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-qrzhwtkm/rpds_py-0.13.2.tar.gz

Exited with code exit status 1
```

**Comment by Julian** [comment]
(Whenever filing a bug report, you need to include what you ran, and how someone else can reproduce.)

You're running things that are very long out of date -- specifically `easy_install` is something you should never run anymore, it's long deprecated (See e.g. the note in https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html or the packaging documentation)

(The same is true of `.egg` files for what it's worth)

Essentially whatever you're running is so old it doesn't know anything about modern Python packaging (with modern there meaning even "the last 5 years").

**Comment by mjallday** [comment]
Thanks @Julian. 

I'm closing since running `pip install .` instead of `python setup.py install` makes this error go away. 🤷🏽‍♀️
