### ISSUE TITLE
Implement __hash__

### ISSUE THREAD

**Issue by Julian** [crate-py/rpds#50]
- [x] Queue
- [ ] HashTrieMap
- [ ] HashTrieSet
- [ ] List

**Comment by qerub** [comment]
I'm not familiar enough with Rust to provide a PR that implements __hash__ for List but I would really appreciate such an addition. :)

**Comment by Julian** [comment]
Hey.

I *think* `List` should be relatively straightforward and basically match what I did for `Queue` (as opposed to the other 2 which require a different approach) -- but I haven't made time to do it, and especially so now that there's some work to figure out how to upgrade to PyO3 0.21...

But I can try to put it on the TODO list.

Can I ask out of curiosity what you're using `rpds.py` for that led you to need it?

**Comment by qerub** [comment]
Sure! I want an immutable list implementation in an application I'm developing and since `rpds-py` is already a (currently transitive) dependency via `jsonschema` it's appealing to use instead of adding yet another dependency like `pyrsistent`.

**Comment by FlickerSoul** [comment]
I can open a PR implementing `__hash__` for list! 

I'm not sure how to implement hash for the `HashTrieMap` and `HashTrieSet` since sequence matters when building a hash from a hasher. The simplest on top of my mind was sort the keys (items) in the map (set) based on their hashes. For example, for map, it could be 

```
hashes = []
FOR key, value IN map:
    hash_tuple = (python_hash(key), python_hash(value))
    
SORT hashes

FOR k_hash, v_hash IN hashes:
    hasher.write_i128( (k_hash << 64) | v_hash )

RETURN hasher.finish()
```

I'm not a cryptography expert so I'm not sure if this is a good idea. :(

**Comment by FlickerSoul** [comment]
I just wrote something for `__hash__` [here](https://github.com/FlickerSoul/rpds/compare/dev...FlickerSoul:rpds:__hash__). I'm curious what you think :) 

Thanks!

**Comment by Julian** [comment]
Hey! Help here would also be great.

For the unordered collections I think the best idea so far is we port the CPython hashing code which is used for `frozenset` -- it can be found here: https://github.com/python/cpython/blob/d69529d31ccd1510843cfac1ab53bb8cb027541f/Objects/setobject.c#L715

**Comment by FlickerSoul** [comment]
Thanks for the direction! I'll take a look :)

**Comment by Julian** [comment]
Thanks to @FlickerSoul this should be done. Please give it a try!
