### ISSUE TITLE
bump pyo3 to minimum 0.20.3?

### ISSUE THREAD

**Issue by he32** [crate-py/rpds#71]
Hi,

I wonder if you could bump the pyo3 revision to at least 0.20.3, so that this can build on hosts which do not support native 64-bit atomic operations?

**Comment by Julian** [comment]
Hi there. We're already on 0.20.3.

**Comment by he32** [comment]
Hm, but not in a tagged release?

**Comment by Julian** [comment]
I've just tagged one then!

**Comment by he32** [comment]
> I've just tagged one then!

Thanks, appreciated!
